### ISSUE TITLE
NullPointerException in watchEvent() method

### ISSUE THREAD

**Issue by zmre** [oncue/knobs#15] opened 2015-08-18 05:14 UTC
Knobs is working well for me and working as expected for my use cases, but I've been seeing a NullPointerException output from a different thread.  Apparently there's an issue in watchEvent and an unhandled error.  As this isn't on the main thread, it doesn't abort any processing and isn't trappable by the calling app (as far as I know).

Here's the exception stack trace:

```
java.lang.NullPointerException
	at knobs.Resource$.watchEvent(Resource.scala:181)
	at knobs.Resource$$anon$1$$anonfun$watch$1$$anonfun$apply$12$$anonfun$apply$13$$anonfun$apply$14.apply(Resource.scala:194)
	at knobs.Resource$$anon$1$$anonfun$watch$1$$anonfun$apply$12$$anonfun$apply$13$$anonfun$apply$14.apply(Resource.scala:194)
	at scalaz.stream.Process$$anonfun$map$1.apply(Process.scala:53)
	at scalaz.stream.Process$$anonfun$map$1.apply(Process.scala:53)
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46)
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.flatMap(Process.scala:46)
	at scalaz.stream.Process$Emit.flatMap(Process.scala:577)
	at scalaz.stream.Process$class.map(Process.scala:53)
	at scalaz.stream.Process$Emit.map(Process.scala:577)
	at knobs.Resource$$anon$1$$anonfun$watch$1$$anonfun$apply$12$$anonfun$apply$13.apply(Resource.scala:194)
	at knobs.Resource$$anon$1$$anonfun$watch$1$$anonfun$apply$12$$anonfun$apply$13.apply(Resource.scala:194)
	at scalaz.concurrent.Task$.Try(Task.scala:386)
	at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:286)
	at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:286)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

And some other details that may be useful: 

Mac OS X 10.10.5
Scala 2.11.7
Knobs 3.3.0
Java 1.8

**Comment by timperrett** [comment] 2015-08-27 06:53
@zmre thanks for the feedback! One of our team will look into it tomorrow (sorry for the delay thus far)

**Comment by zmre** [comment] 2015-08-27 16:02
No problem.  Let me know if you need my help tracking anything down.

**Comment by runarorama** [comment] 2015-08-27 18:04
This appears to be caused by `java.nio.file.Path.getParent` returning `null`, which supposedly happens when the path does not have a parent. Are you somehow using a config file that doesn't have a parent?

**Comment by zmre** [comment] 2015-08-27 20:46
@runarorama: I wouldn't think so, but here's the config that I'm using:

```scala
  private val configFileName = "couchbase.cfg"
  private val configFileDevName = "couchbase-dev.cfg"
  private val config: Task[Config] = knobs.loadImmutable(
    Optional(ClassPathResource(configFileName))
      :: Optional(FileResource(new File(configFileDevName)))
      :: Nil
  )
```

The idea is to load a config file out of the class path and allow overrides if there's an alternate config in the root directory of the project.  This actually works great.  It picks up couchbase-dev.cfg if it exists in the project's root directory and picks up the classpath config file as well.  But I don't specify a path when I create the `new File()`.

**Comment by runarorama** [comment] 2015-08-27 22:05
One issue is that the file watching code expects the path to specify at least a parent directory. We should probably fix that.

In the meantime, I've pushed https://github.com/oncue/knobs/pull/17

**Comment by runarorama** [comment] 2015-08-27 22:06
Leaving open until path issue is solved.

**Comment by runarorama** [comment] 2015-08-27 23:48
Fixed by #18

**Closed by runarorama** 2015-08-27 23:48 UTC

**Comment by runarorama** [comment] 2015-08-27 23:52
OK, the fix for your issue is now several layers deep:

1. `loadImmutable` won't start a watcher anymore.
1. `FileResource.apply` optionally lets you specify that you don't want the file watched.
1. `FileResource.apply` now goes and gets the canonical file name for the path you provide.
1. If you don't use `FileResource.apply`, you will have to supply a canonical file name, and you will get a helpful error message if you don't.

**Comment by zmre** [comment] 2015-08-28 00:54
Fantastic, thanks very much, @runarorama. I'm looking forward to the next release.
